#!/usr/bin/env python3
import sys
import os
import argparse

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, ROOT_DIR)

from src.classification.predict import predict_image

def main():
    parser = argparse.ArgumentParser(
        description="Predict leaf disease class from one image using saved model artifacts."
    )
    parser.add_argument("image_path", help="Path to the source image")
    parser.add_argument(
        "--artifact",
        default=os.path.join(ROOT_DIR, "models/leaf_model.joblib"),
        help="Path to model artifact generated by training (default: models/leaf_model.joblib)",
    )
    parser.add_argument(
        "--output-dir",
        default=os.path.join(ROOT_DIR, "results/prediction"),
        help="Directory where prediction visualizations are saved (default: results/prediction)",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display prediction figure interactively after saving.",
    )
    args = parser.parse_args()

    predict_image(
        image_path=args.image_path,
        artifact=args.artifact,
        output_dir=args.output_dir,
        show=args.show,
    )

if __name__ == "__main__":
    main()
