import argparse
import os

import cv2
import joblib
import matplotlib.pyplot as plt
import numpy as np

from src.classification.features import DEFAULT_IMAGE_SIZE, extract_features
from src.common.mask import (
    DEFAULT_LOWER_GREEN,
    DEFAULT_UPPER_GREEN,
    build_leaf_mask,
)


LOWER_GREEN = DEFAULT_LOWER_GREEN
UPPER_GREEN = DEFAULT_UPPER_GREEN


def _build_preview(image_path):
    original_bgr = cv2.imread(image_path)
    if original_bgr is None:
        raise ValueError(f"Failed to read image: {image_path}")

    resized_bgr = cv2.resize(
        original_bgr,
        (DEFAULT_IMAGE_SIZE, DEFAULT_IMAGE_SIZE),
        interpolation=cv2.INTER_AREA,
    )
    mask = build_leaf_mask(resized_bgr, LOWER_GREEN, UPPER_GREEN)
    masked_bgr = cv2.bitwise_and(resized_bgr, resized_bgr, mask=mask)

    return original_bgr, resized_bgr, mask, masked_bgr


def _save_prediction_figure(image_path, output_dir, predicted_class, confidence):
    original_bgr, resized_bgr, mask, masked_bgr = _build_preview(image_path)

    os.makedirs(output_dir, exist_ok=True)
    base_name = os.path.splitext(os.path.basename(image_path))[0]
    output_path = os.path.join(output_dir, f"prediction_{base_name}.png")

    fig, axes = plt.subplots(1, 4, figsize=(16, 5))
    axes[0].imshow(cv2.cvtColor(original_bgr, cv2.COLOR_BGR2RGB))
    axes[0].set_title("Original")
    axes[0].axis("off")

    axes[1].imshow(cv2.cvtColor(resized_bgr, cv2.COLOR_BGR2RGB))
    axes[1].set_title("Resized (224x224)")
    axes[1].axis("off")

    axes[2].imshow(mask, cmap="gray")
    axes[2].set_title("Leaf Mask")
    axes[2].axis("off")

    axes[3].imshow(cv2.cvtColor(masked_bgr, cv2.COLOR_BGR2RGB))
    axes[3].set_title("Masked Leaf")
    axes[3].axis("off")

    fig.suptitle(
        f"Prediction: {predicted_class} | Confidence: {confidence:.4f}",
        fontsize=12,
    )
    plt.tight_layout()
    plt.savefig(output_path, bbox_inches="tight")
    plt.close(fig)
    return output_path


def _predict_with_confidence(model, feature_vector):
    prediction = model.predict(feature_vector)[0]

    confidence = 1.0
    if hasattr(model, "predict_proba"):
        probabilities = model.predict_proba(feature_vector)[0]
        confidence = float(np.max(probabilities))

    return prediction, confidence


def main():
    parser = argparse.ArgumentParser(
        description="Predict leaf disease class from one image using saved model artifacts."
    )
    parser.add_argument("image_path", help="Path to the source image")
    parser.add_argument(
        "--artifact",
        default="models/leaf_model.joblib",
        help="Path to model artifact generated by training (default: models/leaf_model.joblib)",
    )
    parser.add_argument(
        "--output-dir",
        default="results/prediction",
        help="Directory where prediction visualizations are saved (default: results/prediction)",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display prediction figure interactively after saving.",
    )
    args = parser.parse_args()

    if not os.path.isfile(args.image_path):
        print(f"Error: {args.image_path} is not a valid file.")
        return

    if not os.path.isfile(args.artifact):
        print(f"Error: model artifact not found at {args.artifact}")
        return

    payload = joblib.load(args.artifact)
    model = payload.get("model")
    model_name = payload.get("model_name", "unknown")

    if model is None:
        print("Error: artifact payload does not contain a trained model.")
        return

    feature_vector = extract_features(args.image_path).reshape(1, -1)
    expected_size = payload.get("feature_size")
    if expected_size is not None and feature_vector.shape[1] != expected_size:
        print(
            "Error: feature size mismatch "
            f"(expected {expected_size}, got {feature_vector.shape[1]})."
        )
        return

    predicted_class, confidence = _predict_with_confidence(
        model, feature_vector
    )

    figure_path = _save_prediction_figure(
        args.image_path,
        args.output_dir,
        predicted_class,
        confidence,
    )

    print(f"Model: {model_name}")
    print(f"Predicted class: {predicted_class}")
    print(f"Confidence: {confidence:.4f}")
    print(f"Visualization saved to: {figure_path}")

    if args.show:
        image = plt.imread(figure_path)
        plt.figure(figsize=(14, 5))
        plt.imshow(image)
        plt.axis("off")
        plt.title(f"Prediction: {predicted_class} ({confidence:.4f})")
        plt.tight_layout()
        plt.show()


if __name__ == "__main__":
    main()
